// LOCALHOST
### Get all recipe Public
GET http://localhost:3000/recipes

### Get all recipe Private
GET http://localhost:3000/private

### Get single recipe Public
GET http://localhost:3000/recipes/

### Get single recipe Private
GET http://localhost:3000/private/62894a61eb7f1cc02c8da0d2

### Create contact
POST http://localhost:3000/api/recipeModel HTTP/1.1
Content-Type: application/json

{
    "name": "LOL",
    "ingredients": ["terreell", "pizza"],
    "instructions": "terr@t.com",
    "public": false,
    "img": "02/030",
    "prepTime": "02/030",
      "cookTime": "02/030",
        "servings": "02/030"
}

### Put Contact / update contact
PUT http://localhost:3000/api/recipeModel/put/62771fc8c5f02ba90113805b HTTP/1.1
Content-Type: application/json

  {
    "name": "LOL",
    "ingredients": ["terreell", "pizza"],
    "instructions": "terr@t.com",
    "public": false,
    "img": "02/030",
    "prepTime": "02/030",
      "cookTime": "02/030",
        "servings": "02/030"
  }

### Delete Contact / delete contact
DELETE  http://localhost:3000/api/recipeModel/delete/62771fc8c5f02ba90113805b HTTP/1.1

// PRODUCTION Deploy 
### Get all
GET https://jacob-recipe.herokuapp.com/recipes 
### Get by specific id
GET https://jacob-recipe.herokuapp.com/recipes/628949d2a5d583cb8dd74967 

### Create contact
POST https://jacob-recipe.herokuapp.com/api/recipeModel HTTP/1.1
Content-Type: application/json

{
    "name": "dfhdfgh",
    "ingredients": ["terreell", "pizza"],
    "instructions": "terr@t.com",
    "public": false,
    "img": "02/030",
    "prepTime": "02/030",
      "cookTime": "02/030",
        "servings": "02/030"
}


### Put Contact / update contact
PUT https://jacob-recipe.herokuapp.com/api/recipeModel/put/628948de01efe8208083ee65 HTTP/1.1
Content-Type: application/json

  {
    "name": "herokuPut",
    "ingredients": ["terreell", "pizza"],
    "instructions": "terr@t.com",
    "public": false,
    "img": "02/030",
    "prepTime": "02/030",
      "cookTime": "02/030",
        "servings": "02/030"
  }

### Delete Contact / delete contact
DELETE  https://jacob-recipe.herokuapp.com/api/recipeModel/delete/628948de01efe8208083ee65 HTTP/1.1